version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: local-postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=classifieds-db"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "15432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    container_name: local-redis
    ports:
      - "16379:6379"

volumes:
  pg-data: